print("----------------------------------------------------------------")

#1.Integer (int)
#Whole Numbers (positve / Negitive  / Zero)
X = 10
Y = -50
print("Integet Value :",X,Y)

print("----------------------------------------------------------------")

#2.Float (float)
#Decimal Numbers
PI = 3.14
RATE = -99.99
print("Floating Value :",PI,RATE)

print("----------------------------------------------------------------")

#3.String (str)
#Text / Characters, Single or Double Quotes 
name =  "Hello"
Language = "Python"
print("String Value :",name,Language)

print("----------------------------------------------------------------")

#4.Boolean (bool)
#Only True Or False
It_python = True
It_ok = False
print("Boolean Values :",It_python,It_ok)

print("----------------------------------------------------------------")

#5.List(list)
#Ordered Collection , Changeable Mean Square Brackets []
language = ["C" , "C++" , "SQL" , "PYTHON"]
print("List Value :",language)

print("----------------------------------------------------------------")

#6.Tuple (tuple)
#Ordered Collection No Changeable (immutable),round bracket ()
color = ("red", "green", "Blue")
print("Tuple Values :",color)

print("----------------------------------------------------------------")

#7.Set (set)
#Uordered Collection , Duplicates not allowed curly brackets {}
nums = {10, 20, 30, 20, 10}
print("Set Values :",nums) #{10, 20, 30}

print("----------------------------------------------------------------")

#Dictionary (dict)
#Key - Value pairs, curly brackets {key:value}
student = {"Name" : "Vishwraj", "Age" : 25, "Marks" : 90}
print("Dictionary Values :",student)

print("----------------------------------------------------------------")