#Ek list banao jisme tumhare 5 favourite games ho.
print("\nList")
Games = ["Free Fire" , "PUGB" , "Vice City" , "Puzzle" , "Ruby Cude"]
print("My Favorite 5 Games :",Games)

#Ek tuple banao jisme 3 cities ke naam ho.
print("\nTuple")
city = ("Ahemdabad" , "Gandhinagar" , "Vadodara")
print("Three Cities :",city)

#Ek set banao jisme duplicate numbers ho aur output check karo
print("\nSets")
number = {100, 200, 300, 400, 100, 200}
print("Dupalicate Values Is:",number)

#Ek dictionary banao jisme student ke details ho: name, age, marks.
print("\nDictionary")
student = {"Name" : "Araya", "Age" : 26, "Marks" : 98} 
print("Student Details :",student["Name"])
